export const projects = [
    {id:0, name:'Candle Store', image:'/dimmar.webp',git:'https://github.com/dimtheo6/dimmar-candles',demo:'https://dimmar.netlify.app/',description:"A full-stack e-commerce candle store built with Next.js, TypeScript, and Tailwind CSS. Uses Zustand for state management, Firestore as the backend, Stripe for secure payments, and Resend for automated transactional emails."},
    {id:1, name:'Github Dashboard', image:'/github-dashboard.webp',git:'https://github.com/dimtheo6/github-dashboard',demo:'https://dim-githubdash.netlify.app/',description:"Built with React and Tailwind, this dashboard fetches real-time GitHub data using the REST API. Displays user profiles, repositories, and follower stats with a responsive, dynamic UI."},
    {id:2, name:'Game Store', image:'/shopping-cart.webp',git:'https://github.com/dimtheo6/shopping-cart?tab=readme-ov-file',demo:'https://dimtheoshop-cart.netlify.app/',description:'A responsive e-commerce mockup built with React, Tailwind, and the RAWG API. Features game listings, genre filtering, and dynamic content pulled from a live API.'},
    {id:3, name:'Memory Card', image:'/memory-card.webp',git:'https://github.com/dimtheo6/memory-card',demo:'https://card-memo.netlify.app/',description:'A Pokémon memory game built with React and PokeAPI. Includes over 150 unique characters, randomized cards, and score tracking.'},
    {id:4, name:'CV Generator', image:'/cv-generator.webp',git:'https://github.com/dimtheo6/cv-application',demo:'https://cv-applicationgen.netlify.app/',description:'A real-time CV generator where users can input, edit, and remove their data. Built with React, it updates the preview live and supports structured personal, educational, and work info.'},
    {id:5, name:'Weather App', image:'/weather.webp',git:'https://github.com/dimtheo6/Weather-App',demo:'https://dimtheo6.github.io/Weather-App/',description:'A weather app built with HTML, CSS, and JavaScript. Fetches real-time and weekly forecasts via the OpenWeatherMap API with responsive design and dynamic UI updates.'},
    {id:6, name:'Todo List', image:'/todo.webp',git:'https://github.com/dimtheo6/Todo-List',demo:'https://dimtheo6.github.io/Todo-List/',description:'A simple yet functional task manager built using plain JavaScript. Users can create, edit, and organize tasks with local storage support and a clean, responsive layout.'},
    {id:7, name:'Restaurant Page', image:'/restaurant.webp',git:'https://github.com/dimtheo6/Restaurant-Page',demo:'https://dimtheo6.github.io/Restaurant-Page/',description:'A fully dynamic restaurant homepage built with vanilla JavaScript. Renders pages like Menu, About, and Order Online using DOM manipulation without page reloads.'},
    {id:8, name:'Library', image:'/library.webp',git:'https://github.com/dimtheo6/library',demo:'https://dimtheo6.github.io/library/',description:'A book-tracking app built with JavaScript, HTML, and CSS. Users can add, update, and remove books, with status tracking (read/unread)'},
    {id:9, name:'Tic-Tac-Toe', image:'/tic-tac-toe.webp',git:'https://github.com/dimtheo6/tic-tac-toe',demo:'https://dimtheo6.github.io/tic-tac-toe/',description:'A classic 2-player Tic-Tac-Toe game built using HTML, CSS, and JavaScript. Tracks player turns, detects wins and draws, and resets for replay.'},
]