export const projects = [
    {id:0, name:'Shopping Cart', image:'/shopping-cart.webp',git:'https://github.com/dimtheo6/shopping-cart?tab=readme-ov-file',demo:'https://dimtheoshop-cart.netlify.app/',description:'Is a mock-up of an e-commerce website that sells video game products.'},
    {id:1, name:'Memory Card', image:'/memory-card.webp',git:'https://github.com/dimtheo6/memory-card',demo:'https://card-memo.netlify.app/',description:'A pokemon themed memory game, it features over 150 unique pokemon via PokeAPI.'},
    {id:2, name:'CV Generator', image:'/cv-generator.webp',git:'https://github.com/dimtheo6/cv-application',demo:'https://cv-applicationgen.netlify.app/',description:'A simple CV generator, users can input, edit and delete their information in real time.'},
    {id:3, name:'Weather App', image:'/weather.webp',git:'https://github.com/dimtheo6/Weather-App',demo:'https://dimtheo6.github.io/Weather-App/',description:'Get current and weekly forecast worldwide in real time.'},
    {id:4, name:'Todo List', image:'/todo.webp',git:'https://github.com/dimtheo6/Todo-List',demo:'https://dimtheo6.github.io/Todo-List/',description:'A simple web app to create, organize and manage your tasks.'},
    {id:5, name:'Restaurant Page', image:'/restaurant.webp',git:'https://github.com/dimtheo6/Restaurant-Page',demo:'https://dimtheo6.github.io/Restaurant-Page/',description:'Dynamically rendered restaurant homepage using javascript.'},
    {id:6, name:'Library', image:'/library.webp',git:'https://github.com/dimtheo6/library',demo:'https://dimtheo6.github.io/library/',description:'A simple library page to store books you plan to read or have already read.'},
    {id:7, name:'Tic-Tac-Toe', image:'/tic-tac-toe.webp',git:'https://github.com/dimtheo6/tic-tac-toe',demo:'https://dimtheo6.github.io/tic-tac-toe/',description:'Play the classic Tic-Tac-Toe game online! Challenge a friend on a 3x3 grid.'},
]